movie/urls.py
from django.urls import path 
from .import views

app_name = 'movie'

urlpatterns = [
	path('', views.HomePageView.as_view(), name='home'),
	path('movie/<slug:slug>', views.MovieDetailView.as_view(), name='movie_detail'),
	path('contact/', views.contact, name='contact'),

	#News url 
	path('posts/', views.AllPostView.as_view(), name='posts'),
	path('post/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'),
	path('posts/<slug:category_slug>', views.getCatPost, name='category_posts'),
	path('tags/<slug:tag_slug>', views.getTagPost, name='tag_posts'),

	#Genres and Ctegories
	path('janr/<slug:genre>', views.genreDetail, name='genre_detail'),

	#Search  and other utils
	path('search/', views.search, name='search'),
	path('movies/', views.movies, name='movies'),
]

onemovie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('movie.urls', namespace='movie')),
    path('', include('social_django.urls', namespace='social'))
]

handler404 = 'movie.views.customHandler404'

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

# *Category => name , slug
# *Genre => name,slug
# *Actors => name,slug,age,country,bio,films, image
# *Movie => title,slug,country,genre,year,budget, actors,producer,poster
# *Comment => name,message
# *Contact => fname,lname,email,subject,message

class Category(models.Model):
	name = models.CharField("Kategoriya nomi", max_length=150)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Kategoriya'
		verbose_name_plural = 'Kategoriyalar'


class Genre(models.Model):
	name = models.CharField("Janr nomi", max_length=150)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('movie:genre_detail', kwargs={'genre':self.slug})

	class Meta:
		verbose_name = 'Janr'
		verbose_name_plural = 'Janrlar'

class Actors(models.Model):
	name = models.CharField('Ismi', max_length=150)
	slug = models.SlugField('*', max_length=100, unique=True)
	age = models.PositiveIntegerField('Yoshi', default=0, blank=True)
	country = models.CharField('Millati', max_length=100, blank=True)
	bio = models.TextField('Biografiya')
	image = models.ImageField('Rasmi', upload_to='actors/')
	# movies = models.ForeignKey(Movie, on_delete=models.PROTECT)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Aktyor'
		verbose_name_plural = 'Aktyorlar'

# class Rating(models.Model):



class Movie(models.Model):
	title = models.CharField('Kino nomi', max_length=250)
	slug = models.SlugField('*', max_length=100, unique=True)
	genre = models.ForeignKey(Genre, on_delete=models.PROTECT, related_name='genres')
	poster = models.ImageField('Poster', upload_to='movies/')
	director = models.CharField('Rejissor', max_length=100)
	trailer_link = models.CharField('You tube link', max_length=100)
	actors = models.ForeignKey(Actors, on_delete=models.PROTECT, related_name='actors')
	country = models.CharField('Davlati', max_length=100, blank=True)
	year = models.PositiveIntegerField('Yili', default=2021)
	budget = models.PositiveIntegerField('Byudjet', default=0)
	rating = models.DecimalField('Reyting',max_digits=5, decimal_places=2)
	views = models.PositiveIntegerField('Korildi', default=0)
	banner = models.ImageField('Rasm',upload_to='banner/')
	xaqida = models.TextField('Kino xaqida')


	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Kino'
		verbose_name_plural = 'Kinolar'




class Comment(models.Model):
	movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
	name = models.CharField('Ism-Familya', max_length=100)
	message = models.TextField('Xabar')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

class Contact(models.Model):
	first_name = models.CharField("Ism", max_length=30)
	last_name = models.CharField("Familya", max_length=30)
	email = models.EmailField('Email')
	subject = models.CharField('Mavzu', max_length=150)
	message = models.TextField('Xabar')

	def __str__(self):
		return self.first_name

	class Meta:
		verbose_name = 'Aloqa'
		verbose_name_plural = 'Aloqalar'

# Blog 

class PostCategory(models.Model):
	name = models.CharField('Post Category name', max_length=100)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return  reverse('movie:category_posts', kwargs={'category_slug':self.slug})

	class Meta:
		verbose_name = 'Maqola Kategoriya'
		verbose_name_plural = 'Maqolalar Kategoriyalari'


class Tags(models.Model):
	name = models.CharField('Post Tag name', max_length=100)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return  reverse('movie:tag_posts', kwargs={'tag_slug':self.slug})

	class Meta:
		verbose_name = 'Maqola Tegi'
		verbose_name_plural = 'Maqolalar Teglari'

class Post(models.Model):
	title = models.CharField('Maqola nomi', max_length=450)
	slug = models.SlugField('*', max_length=100, unique=True)
	category = models.ForeignKey(
		PostCategory, 
		on_delete=models.CASCADE, 
		related_name='posts'
		)
	tag = models.ManyToManyField(Tags, related_name='posts')
	views = models.PositiveIntegerField('Views', default=0)
	top = models.BooleanField('Top post', default=False)
	body = models.TextField('Matni')
	image = models.ImageField('Poster', upload_to='post_posters/')
	author = models.CharField('Muallif', max_length=50)
	published = models.DateTimeField("Qo'shilgan sana", auto_now_add=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'
		ordering = ['-id']

movie/forms.py
from django import forms 
from .models import Movie, Contact

class MovieRatingForm(forms.ModelForm):
	class Meta:
		model = Movie 
		fields = ['rating']


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'
		

movie/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from .models import *

from .forms import MovieRatingForm, ContactForm 
import telebot



bot = telebot.TeleBot('1999276041:AAHfSSl9PbV3XlAKUTlDbWVPiYxr4HG5diI')
my_id = 696007117
class HomePageView(View):
	# Home Page Movies View
	def get(self,request):
		form = MovieRatingForm(request.GET)
		if form.is_valid():
			form.save()
		else:
			form = MovieRatingForm()
		movie = Movie.objects.all()
		top_viewed = Movie.objects.all().order_by('-views')[:6]
		recent_add = Movie.objects.all().order_by('-id')[:6]
		random_movies = Movie.objects.all().order_by('?')[:6]
		fantastic_movies = Movie.objects.all().order_by('-id')[:6]
		zombie_movies = Movie.objects.all().order_by('-id')[6:]
		all_movies = Movie.objects.all().order_by('-id')
		for x in all_movies:
			print(x.title)

			
		context = {
			'top_viewed':top_viewed,
			'movies':movie,
			'recent_add':recent_add,
			'random_movies':random_movies,
			'form':form,
			'fantastic_movies':fantastic_movies,
			'zombie_movies':zombie_movies,
			'all_movies':all_movies,
		}
		return render(request, 'index.html', context)


class MovieDetailView(DetailView):
	model = Movie
	template_name = 'single.html'
	slug_field = 'slug'

# class ContactPageView(View):
# 	def get(self, request):
# 		form = ContactForm()
# 		context = {'form': form}
# 		return render(request, 'contact.html', context)

# 	def post(self, request):
# 		form = ContactForm(request.POST)
# 		if form.is_valid():
# 			form.save()
# 			return render(request, 'contact.html')
# 		else:
# 			form = ContactForm()
# 			context = {'form': form}
# 		return render(request, 'contact.html', context)

def contact(request):
	if request.method == 'POST':
		first_name = request.POST['name']
		last_name = request.POST['last_name']
		email = request.POST['email']
		phone = request.POST['phone']
		message = request.POST['message']
		Contact.objects.create(first_name=first_name,last_name=last_name,subject=phone,email=email,message=message)
		bot.send_message(my_id,f"Saytdan xabar bor\nIsmi:  {first_name} \n Familiyasi: {last_name}\n Telfon raqami:  {phone}\nEmail:  {email}\n Xabari:  {message}")
		print('>>>>\n'*30)

	else:
		print('xxxxxxx\n'*30)
	return render(request,'aloqalar.html')
# Test  views 

class AllPostView(ListView):
	model = Post
	paginated_by = 10
	template_name = 'news.html'
	context_object_name = 'posts'

class PostDetailView(DetailView):
	model = Post
	slug_field = 'slug'
	template_name = 'news-single.html'


def getCatPost(request,category_slug):
	category = PostCategory.objects.get(slug=category_slug)
	posts = category.posts.all
	return render(request, 'cat_post.html', {'posts':posts})

def getTagPost(request,tag_slug):
	tag = Tags.objects.get(slug=tag_slug)
	posts = tag.posts.all()
	return render(request, 'cat_post.html', {'posts':posts})



# Genres And Categories

def genreDetail(request, genre):
	genre = get_object_or_404(Genre, slug=genre)
	movie = Movie.objects.filter(genre=genre)
	context = {
		'movie':movie
	}
	return render(request, 'genres.html', context)


def search(request):
	q = request.GET.get('search', None)
	movies = Movie.objects.filter(title__icontains=q)
	posts = Post.objects.filter(title__icontains=q)
	total_results = len(movies) + len(posts)
	query = request.GET['search']
	context = {
		'movies':movies,
		'posts':posts,
		'total_results':total_results,
		'query':query
	}
	return render(request, 'searchResult.html', context)



def movies(request):
	return render(request, 'movies.html')


# Errors 

def customHandler404(request, exception=None):
	return render(request, '404.html')

templates/cat_post.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	{% for post in posts %}
	<ul>
		<li>
			<img width="400" height="auto" src="{{post.image.url}}" alt="">
		</li>
		<li>
			<h4>{{post.title}}</h4>
		</li>
		<li>
			{{post.body}}
		</li>
	</ul>
	{% endfor %}
</body>
</html>

templates/genres.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
<div class="general_social_icons">
	<nav class="social">
		<ul>
			<li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
			<li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
			<li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
			<li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>				  
		</ul>
  </nav>
</div>
<!-- /w3l-medile-movies-grids -->
	<div class="general-agileits-w3l">
		<div class="w3l-medile-movies-grids">

				<!-- /movie-browse-agile -->
				
				      <div class="movie-browse-agile">
					     <!--/browse-agile-w3ls -->
						<div class="browse-agile-w3ls general-w3ls">
								<div class="tittle-head">
									<h4 class="latest-text">Family Movies </h4>
									<div class="container">
										<div class="agileits-single-top">
											<ol class="breadcrumb">
											  <li><a href="index.html">Home</a></li>
											  <li class="active">Genres</li>
											</ol>
										</div>
									</div>
								</div>
						<div class="container">
							<div class="browse-inner">
								
					{% for movie in movie %}
							   <div class="col-md-2 w3l-movie-gride-agile">
							   	
										 <a href="{% url 'movie:movie_detail' movie.slug %}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" alt=" " style="width: 100%; height: auto;" />
									     <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
									</a>
									  <div class="mid-1">
										<div class="w3l-movie-text">
											<h6><a href="{% url 'movie:movie_detail' movie.slug %}">{{movie.title}}</a></h6>							
										</div>
										<div class="mid-2">
										
											<p>{{movie.year}}</p>
											<div class="block-stars">
												<ul class="w3l-ratings">
													     <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star-o" aria-hidden="true"></i></a></li>
														  
										
												</ul>
											</div>
											<div class="clearfix"></div>
										</div>
											
									</div>
							 	    <div class="ribben two">
										<p>Yangi</p>
									</div>	
							</div>
					{% endfor %} 
									
								</div>

								<div class="clearfix"> </div>

							</div>
						</div>
				<!--//browse-agile-w3ls -->
						<div class="blog-pagenat-wthree">
							<ul>
								<li><a class="frist" href="#">Prev</a></li>
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">5</a></li>
								<li><a class="last" href="#">Next</a></li>
							</ul>
						</div>
					</div>
				    <!-- //movie-browse-agile -->
				   <!--body wrapper start-->
				<!--body wrapper start-->
					<div class="review-slider">
						 <h4 class="latest-text">Movie Reviews</h4>
						       <div class="container">
						 		<div class="w3_agile_banner_bottom_grid">
				<div id="owl-demo" class="owl-carousel owl-theme">
					{% for movie in movies %}
					<div class="item">
						<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
							<a href="{% url 'movie:movie_detail' movie.slug %}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" class="img-responsive" alt=" " />
								<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
							</a>
							<div class="mid-1 agileits_w3layouts_mid_1_home">
								<div class="w3l-movie-text">
									<h6><a href="{% url 'movie:movie_detail' movie.slug %}">{{movie.title}}</a></h6>							
								</div>
								<div class="mid-2 agile_mid_2_home">
									<p>{{movie.year}}</p>
									<div class="block-stars">
										<ul class="w3l-ratings">
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
										</ul>
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="ribben">
								<p>Yangi</p>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
						<!--body wrapper end-->
					</div>	
			</div>	
		</div>
	<!-- //w3l-medile-movies-grids -->
	</div>
	<!-- //comedy-w3l-agileits -->
{% endblock %}

templates/movies.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
<div class="general_social_icons">
	<nav class="social">
		<ul>
			<li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
			<li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
			<li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
			<li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>				  
		</ul>
  </nav>
</div>
<!-- /w3l-medile-movies-grids -->
	<div class="general-agileits-w3l">
		<div class="w3l-medile-movies-grids">

				<!-- /movie-browse-agile -->
				
				      <div class="movie-browse-agile">
					     <!--/browse-agile-w3ls -->
						<div class="browse-agile-w3ls general-w3ls">
								<div class="tittle-head">
									<h4 class="latest-text">Barcha Kinolar</h4>
									<div class="container">
										<div class="agileits-single-top">
											<ol class="breadcrumb">
											  <li><a href="{% url 'movie:home' %}">Home</a></li>
											  <li class="active">Kinolar</li>
											</ol>
										</div>
									</div>
								</div>
						<div class="container">
							<div class="browse-inner">
								
					{% for movie in all_movies %}
							   <div class="col-md-2 w3l-movie-gride-agile">

							   	
										 <a href="{% url 'movie:movie_detail' movie.slug %}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" alt=" " style="width: 100%; height: auto;" />
									     <div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
									</a>
									  <div class="mid-1">
										<div class="w3l-movie-text">
											<h6><a href="{% url 'movie:movie_detail' movie.slug %}">{{movie.title}}</a></h6>							
										</div>
										<div class="mid-2">
										
											<p>{{movie.year}}</p>
											<div class="block-stars">
												<ul class="w3l-ratings">
													     <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
														 <li><a href="#"><i class="fa fa-star-o" aria-hidden="true"></i></a></li>
														  
										
												</ul>
											</div>
											<div class="clearfix"></div>
										</div>
											
									</div>
							 	    <div class="ribben two">
										<p>Yangi</p>
									</div>	
							</div>
					{% endfor %} 
									
								</div>

								<div class="clearfix"> </div>

							</div>
						</div>
				<!--//browse-agile-w3ls -->
						<div class="blog-pagenat-wthree">
							<ul>
								<li><a class="frist" href="#">Prev</a></li>
								<li><a href="#">1</a></li>
								<li><a href="#">2</a></li>
								<li><a href="#">3</a></li>
								<li><a href="#">4</a></li>
								<li><a href="#">5</a></li>
								<li><a class="last" href="#">Next</a></li>
							</ul>
						</div>
					</div>
				    <!-- //movie-browse-agile -->
				   <!--body wrapper start-->
				<!--body wrapper start-->
					<div class="review-slider">
						 <h4 class="latest-text">Movie Reviews</h4>
						       <div class="container">
						 		<div class="w3_agile_banner_bottom_grid">
				<div id="owl-demo" class="owl-carousel owl-theme">
					{% for movie in movies %}
					<div class="item">
						<div class="w3l-movie-gride-agile w3l-movie-gride-agile1">
							<a href="{% url 'movie:movie_detail' movie.slug %}" class="hvr-shutter-out-horizontal"><img src="{{movie.poster.url}}" title="album-name" class="img-responsive" alt=" " />
								<div class="w3l-action-icon"><i class="fa fa-play-circle" aria-hidden="true"></i></div>
							</a>
							<div class="mid-1 agileits_w3layouts_mid_1_home">
								<div class="w3l-movie-text">
									<h6><a href="{% url 'movie:movie_detail' movie.slug %}">{{movie.title}}</a></h6>							
								</div>
								<div class="mid-2 agile_mid_2_home">
									<p>{{movie.year}}</p>
									<div class="block-stars">
										<ul class="w3l-ratings">
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star" aria-hidden="true"></i></a></li>
											<li><a href="#"><i class="fa fa-star-half-o" aria-hidden="true"></i></a></li>
										</ul>
									</div>
									<div class="clearfix"></div>
								</div>
							</div>
							<div class="ribben">
								<p>Yangi</p>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
						<!--body wrapper end-->
					</div>	
			</div>	
		</div>
	<!-- //w3l-medile-movies-grids -->
	</div>
	<!-- //comedy-w3l-agileits -->
{% endblock %}

templates/news.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
<!-- //nav -->
<div class="general_social_icons">
	<nav class="social">
		<ul>
			<li class="w3_twitter"><a href="#">Twitter <i class="fa fa-twitter"></i></a></li>
			<li class="w3_facebook"><a href="#">Facebook <i class="fa fa-facebook"></i></a></li>
			<li class="w3_dribbble"><a href="#">Dribbble <i class="fa fa-dribbble"></i></a></li>
			<li class="w3_g_plus"><a href="#">Google+ <i class="fa fa-google-plus"></i></a></li>				  
		</ul>
  </nav>
</div>
<!-- faq-banner -->
	<div class="faq">
			<div class="container">
				<div class="agileits-news-top">
					<ol class="breadcrumb">
					  <li><a href="{% url 'movie:home' %}">Home</a></li>
					  <li class="active">News</li>
					</ol>
				</div>
				<div class="agileinfo-news-top-grids">
					<div class="col-md-8 wthree-top-news-left">
						<div class="wthree-news-left">
							<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
								<ul id="myTab" class="nav nav-tabs" role="tablist">
									<li role="presentation" class="active"><a href="#home1" id="home1-tab" role="tab" data-toggle="tab" aria-controls="home1" aria-expanded="true">Latest News</a></li>
									<li role="presentation"><a href="#w3bsd" role="tab" id="w3bsd-tab" data-toggle="tab" aria-controls="w3bsd">Movie News</a></li>
								</ul>
								<div id="myTabContent" class="tab-content">
									<div role="tabpanel" class="tab-pane fade in active" id="home1" aria-labelledby="home1-tab">
						

			{% for post in posts %}											
			<div class="wthree-news-top-left">
				<div class="col-md-12 w3-agileits-news-left">
					<div class="col-sm-5 wthree-news-img">
						<a href="{% url 'movie:post_detail' post.slug %}">
							<img width="100%" height="auto" src="{{post.image.url}}" alt="" />
						</a>
					</div>
					<div class="col-sm-7 wthree-news-info">
						<h5><a href="{% url 'movie:post_detail' post.slug %}">{{post.title}}</a></h5>
						<p>{{post.body|truncatewords:'10'}}</p>
						<ul>
							<li><i class="fa fa-clock-o" aria-hidden="true"></i> {{post.published}}</li>
							<li><i class="fa fa-eye" aria-hidden="true"></i> {{post.view}}</li>
						</ul>
					</div>
					<div class="clearfix"> </div>
				</div>

			</div>
				<div class="clearfix"> </div>
				<br>
				<br>
			{% endfor %}

									</div>
					
								</div>
							</div>
						</div>
					</div>
					<div class="col-md-4 wthree-news-right">
						<!-- news-right-top -->
						<div class="news-right-top">
							<div class="wthree-news-right-heading">
								<h3>Latest News</h3>
							</div>
							<div class="wthree-news-right-top">
								<div class="news-grids-bottom">
									<!-- date -->
									<div id="design" class="date">
										<div id="cycler">  					{% for post in latest_post %}									
												<div class="date-text">
													<a href="{{post.get_absolute_url}}">{{post.published}}</a>
													<p>{{post.title}}</p>
												</div>
											{% endfor %}				
					
										</div>
										<script>
										function blinker() {
											$('.blinking').fadeOut(500);
											$('.blinking').fadeIn(500);
										}
										setInterval(blinker, 1000);
										</script>
										<script>
											function cycle($item, $cycler){
												setTimeout(cycle, 2000, $item.next(), $cycler);
												
												$item.slideUp(1000,function(){
													$item.appendTo($cycler).show();        
												});
												}
											cycle($('#cycler div:first'),  $('#cycler'));
										</script>
									</div>
									<!-- //date -->
								</div>
							</div>
						</div>
						<!-- //news-right-top -->
						<!-- news-right-bottom -->
						<div class="news-right-bottom">
							<div class="wthree-news-right-heading">
								<h3>Top News</h3>
							</div>
							<div class="news-right-bottom-bg">
								<div class="news-grids-bottom">
									{% for post in top_post %}	
									<div class="top-news-grid">
										<div class="top-news-grid-heading">
											<a href="{{post.get_absolute_url}}">{{post.title}}</a>
										</div>
										<div class="w3ls-news-t-grid top-t-grid">
											<ul>
												<li><a href="#"><i class="fa fa-clock-o"></i> {{post.published}}</a></li>
												<li><a href="#"><i class="fa fa-user"></i> {{post.author}}</a></li>
											</ul>
										</div>
									</div>
									{% endfor %}	
								</div>
							</div>
						</div>
						<!-- //news-right-bottom -->
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
	</div>
<!-- //faq-banner -->
{% endblock %}

templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	{% for object in object_list %}
	<ul>
		<li>
			<img width="400" height="auto" src="{{object.image.url}}" alt="">
		</li>
		<li>
			<h4>{{object.title}}</h4>
		</li>
		<li>
			{{object.body}}
		</li>
		<li>
			<h4>Category: </h4>
			<a href="{{object.category.get_absolute_url}}">{{object.category.name}}</a>
		</li>
	</ul>
	{% endfor %}
</body>
</html>